name: flutter_bootcamp2023
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: ">=3.1.0 <4.0.0"

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.2
    flutter_svg: ^2.0.7
    math_expressions: ^2.4.0

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true

    assets:
        - assets/
        - assets/day7/
        - assets/day7/svg_mood_bad.svg
        - assets/day7/svg_mood.svg

    fonts:
        - family: Pacifico
          fonts:
              - asset: fonts/Pacifico-Regular.ttf
